<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-193VCU3" failures="2" tests="14" name="scripts.ContactPage_T_C" time="141.292" errors="0" timestamp="2024-05-03T16:48:30 IST" skipped="0">
  <testcase classname="scripts.ContactPage_T_C" name="serverSideValidationWithInvalidDetails" time="9.329"/>
  <testcase classname="scripts.ContactPage_T_C" name="serverSideValidationWithValidDetails" time="11.148"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyTitleRepetition" time="9.887"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyConsole" time="9.243"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyProtocol" time="11.996"/>
  <testcase classname="scripts.ContactPage_T_C" name="clientSideValidation" time="9.053"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyOgUrlRepetition" time="8.870"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyHttpInPageSource" time="8.214">
    <failure message="The following asserts failed:
	expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at scripts.ContactPage_T_C.verifyHttpInPageSource(ContactPage_T_C.java:147)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- verifyHttpInPageSource -->
  <testcase classname="scripts.ContactPage_T_C" name="verifyDescRepetition" time="11.144"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyNetworkStatus" time="12.344"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifySubdomain" time="8.944"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyMailId" time="12.329"/>
  <testcase classname="scripts.ContactPage_T_C" name="validateErrorMessages" time="8.560"/>
  <testcase classname="scripts.ContactPage_T_C" name="verifyMetaContent" time="10.231">
    <failure message="The following asserts failed:
	Get in touch with our friendly customer service representatives for assistance with your job search journey or any other inquiries on our Contact Us page. Get in touch with us for job search support, feedback, or inquiries. Our team is here to assist you with any questions. Contact us and we&#039;ll be happy to help. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Get in touch with our friendly customer service representatives for assistance with your job search journey or any other inquiries on our Contact Us page. Get in touch with us for job search support, feedback, or inquiries. Our team is here to assist you with any questions. Contact us and we'll be happy to help. expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at scripts.ContactPage_T_C.verifyMetaContent(ContactPage_T_C.java:138)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- verifyMetaContent -->
</testsuite> <!-- scripts.ContactPage_T_C -->
